#!/bin/bash
#
# Copyright (C) 2015 The AmmoniaOS Project
# Copyright (C) 2018 The SudaMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

PROJECTPATH=(
 $ANDROID_BUILD_TOP/build/make
 $ANDROID_BUILD_TOP/frameworks/base
 $ANDROID_BUILD_TOP/packages/apps/Calendar
 $ANDROID_BUILD_TOP/packages/apps/Contacts
 $ANDROID_BUILD_TOP/packages/apps/Dialer
 $ANDROID_BUILD_TOP/packages/apps/Eleven
 $ANDROID_BUILD_TOP/packages/apps/Messaging
 $ANDROID_BUILD_TOP/packages/apps/Settings
 $ANDROID_BUILD_TOP/packages/apps/LineageParts
 $ANDROID_BUILD_TOP/packages/apps/Trebuchet
 $ANDROID_BUILD_TOP/packages/providers/ContactsProvider
 $ANDROID_BUILD_TOP/packages/services/Telecomm
 $ANDROID_BUILD_TOP/vendor/lineage
 $ANDROID_BUILD_TOP/system/core
)

PROJECTLIST=(
 android_build.git
 android_frameworks_base.git
 android_packages_apps_Calendar.git
 android_packages_apps_Contacts.git
 android_packages_apps_Dialer.git
 android_packages_apps_Eleven.git
 android_packages_apps_Messaging.git
 android_packages_apps_Settings.git
 android_packages_apps_LineageParts.git
 android_packages_apps_Trebuchet.git
 android_packages_providers_ContactsProvider.git
 android_packages_services_Telecomm.git
 android_vendor_lineage.git
 android_system_core.git
)

project=0
auto=0

echo -e "\\033[2J"

if [ ! -z "$1" ]; then
     echo "Start repo sync -j$1, Please wait for a while..."
     repo sync -j$1
     read -p "Start to merge ?[y/n]" No
     if [ "$No" = n ]; then
          exit 1
     fi
fi

function doName() {
     PUSHNAME="sdhz152/${PROJECTLIST[project]}"
     PULLNAME="Lineageos/${PROJECTLIST[project]}"
}

function doMerge() {
     if [ "$Yes" = y ] || [ "$Yes" = "" ]; then
          cd $i
          doName
          git pull https://github.com/$PULLNAME lineage-17.1 && echo "" || exit 1
          git commit -am "Merge branch 'lineage-17.1' into lineage-17.1"
          git push https://github.com/$PUSHNAME HEAD:lineage-17.1 && echo "" || exit 1
          cd $ANDROID_BUILD_TOP
     elif [ "$Yes" = e ]; then
            exit 1
     fi
}

read -p "The main code is clean, automatic merging ?[y/n]" Auto
if [ "$Auto" = y ] || [ "$Auto" = "" ]; then
     auto=`expr $auto + 1`;
fi

for i in ${PROJECTPATH[@]}; do
     if [ ! -d $i ]; then
	  echo "$i,Did not find the directory!"
	  exit 1
     else
          if [ "$auto" != 0 ]; then
               yes | read -p "$i,Pull ${PROJECTLIST[project]} ?[y/n/e]" Yes
          else
               read -p "$i,Pull ${PROJECTLIST[project]} ?[y/n/e]" Yes
          fi
          doMerge
          project=`expr $project + 1`;
fi
done
